apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app2
  namespace: argocd-system
spec:
  project: default
  source:
    repoURL: https://github.com/danielbud/argocd-root.git
    targetRevision: HEAD
    path: atlas-staging-app/sample-app
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
